# Generated by Django 5.1.6 on 2025-02-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('coordinates', models.TextField()),
                ('elevation', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
